apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "kubedevnews"
            - name: POSTGRES_PASSWORD
              value: "kubedevnews123"
            - name: POSTGRES_DB
              value: "kubedevnews"
          volumeMounts:
            - name: postgre-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgre-data
          persistentVolumeClaim:
            claimName: postgre-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgre
  labels:
    app: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      targetPort: 5432